codingminds_cappstone
FrankMugagga/codingminds_capstone pull request #2
Opened 2023-02-16 15:10 UTC by FrankMugagga

I created tow pages;About and home that are responsive for a summit: Coding Minds International Summit 2015
When you click on the logo, it redirects you to the home page
The project is also with a mobile menu that can redirect to both the home page and about page
There is a section called featured speakers that loads dynamically

2023-02-16 16:55 UTC, mukhammadrizooff requested changes
Hi @FrankMugagga, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 
- Descriptive `Commit` history ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 16:55 UTC, mukhammadrizooff commented on index.html
> +            </nav>
- [ ] [REQUIRED] Good job so far! Please remove white `space` on top of your `header` part and also please `add` correct design to your main `navigation` elements like a [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/219429215-6db8d3ce-0ae6-4f44-8013-dcdbd240e21c.png)

2023-02-16 16:55 UTC, mukhammadrizooff commented on index.html
> +            </h2>
- [ ] [REQUIRED] Good job so far! Please add `orange line` under to `heading` like a [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/219430301-4c8fc2ad-867a-4524-87d3-0a1d4c0bcf56.png)

2023-02-16 16:55 UTC, mukhammadrizooff commented on index.html
> +            <h3 class="speaker_header">Featured Speakers</h3>
- [ ] [REQUIRED] Good job so far! Kindly add correct `design`(color, fonts...) like a [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/219431219-66b615d7-459b-46cb-bbc5-87cc0f44a593.png)

2023-02-16 16:55 UTC, mukhammadrizooff commented on index.html
> +            </div>  -->
- [ ] [REQUIRED] Please remove `Unnecessary` comments 🙏🏼

2023-02-16 16:55 UTC, mukhammadrizooff commented on about.html
> +                    <div class="logo_date">14th-17th Oct | K'la, Uganda</div>
- [ ] [REQUIRED] Good job so far! Please fix space `arrangement of elements`  on mobile version like a [Behance](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), I `compare` and `highlight` mistakes below the picture:

![image](https://user-images.githubusercontent.com/63915024/219432464-2741eefb-72bb-4caf-8676-951f3eab295b.png)

2023-02-16 16:55 UTC, mukhammadrizooff commented on about.html
> +                </div>
- [ ] [REQUIRED] Good job so far! Please `add` required color fiter to your 2 pictures like a [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 🙏🏼 


![image](https://user-images.githubusercontent.com/63915024/219433185-188e83d1-0d97-464b-9ce4-db7c2074359a.png)

2023-02-16 16:55 UTC, mukhammadrizooff commented on about.html
> +            </div>
- [ ] [REQUIRED] Good job so far! Kindly `About` page's footer colors different than `Home` page but you use same design both pages therfore please fix it  and check again [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/219433913-bb6e0d89-a632-4967-aa8e-48e4294f7df8.png)

2023-02-17 11:28 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @FrankMugagga , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] Check the comments under the review.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2023-02-17 12:01 UTC, merged